### PR TITLE
Added qemu support

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by zigg** [comment]
Hi @thypon,

Thanks for the contribution!  I'm not very familiar with `qemu`, but I thought I'd give this build a shot to see how it worked.  I installed `qemu` from Homebrew (which appears to be version 2.2.0) on my MacBook and attempted a build:

```
$ packer build -only=qemu openbsd-5.6-i386.json
qemu output will be in this color.

==> qemu: Downloading or copying ISO
    qemu: Downloading or copying: http://ftp.openbsd.org/pub/OpenBSD/5.6/i386/install56.iso
==> qemu: Creating hard drive...
==> qemu: Found port for SSH: 3499.
==> qemu: Looking for available port between 5900 and 6000
==> qemu: Found available VNC port: 5987
==> qemu: Starting VM, booting from CD-ROM
==> qemu: Overriding defaults Qemu arguments with QemuArgs...
==> qemu: Error launching VM: Qemu failed to start. Please run with logs to get more info.
==> qemu: Deleting output directory...
Build 'qemu' errored: Build was halted.

==> Some builds didn't complete successfully and had errors:
--> qemu: Build was halted.

==> Builds finished but no artifacts were created.
```

Any insight?  What platform are you building this on?

**Comment by tmatilai** [comment]
I've neither never used qemu, but I'm more than fine adding support to it. Would of course nice if I can build and publish the images for it, too.

**Comment by thypon** [comment]
Have you tried with the "-debug" flag?

I can't understand where qemu fails, but maybe i've added some linux specific qemu flags.

**Comment by zigg** [comment]
@thypon: tried with `-debug`; unfortunately, not much is improved:

```
 packer build -debug -only=qemu openbsd-5.6-i386.json
Debug mode enabled. Builds will not be parallelized.
qemu output will be in this color.

==> qemu: Downloading or copying ISO
    qemu: Downloading or copying: http://ftp.openbsd.org/pub/OpenBSD/5.6/i386/install56.iso
==> qemu: Pausing after run of step 'StepDownload'. Press enter to continue.
==> qemu: Pausing after run of step 'stepPrepareOutputDir'. Press enter to continue.
==> qemu: Pausing after run of step 'StepCreateFloppy'. Press enter to continue.
==> qemu: Creating hard drive...
==> qemu: Pausing after run of step 'stepCreateDisk'. Press enter to continue.
==> qemu: Pausing after run of step 'stepCopyDisk'. Press enter to continue.
==> qemu: Pausing after run of step 'stepResizeDisk'. Press enter to continue.
==> qemu: Pausing after run of step 'stepHTTPServer'. Press enter to continue.
==> qemu: Found port for SSH: 3499.
==> qemu: Pausing after run of step 'stepForwardSSH'. Press enter to continue.
==> qemu: Looking for available port between 5900 and 6000
==> qemu: Found available VNC port: 5987
==> qemu: Pausing after run of step 'stepConfigureVNC'. Press enter to continue.
==> qemu: Starting VM, booting from CD-ROM
==> qemu: Overriding defaults Qemu arguments with QemuArgs...
==> qemu: Error launching VM: Qemu failed to start. Please run with logs to get more info.
==> qemu: Pausing before cleanup of step 'stepConfigureVNC'. Press enter to continue.
==> qemu: Pausing before cleanup of step 'stepForwardSSH'. Press enter to continue.
==> qemu: Pausing before cleanup of step 'stepHTTPServer'. Press enter to continue.
==> qemu: Pausing before cleanup of step 'stepResizeDisk'. Press enter to continue.
==> qemu: Pausing before cleanup of step 'stepCopyDisk'. Press enter to continue.
==> qemu: Pausing before cleanup of step 'stepCreateDisk'. Press enter to continue.
==> qemu: Pausing before cleanup of step 'StepCreateFloppy'. Press enter to continue.
==> qemu: Pausing before cleanup of step 'stepPrepareOutputDir'. Press enter to continue.
==> qemu: Deleting output directory...
==> qemu: Pausing before cleanup of step 'StepDownload'. Press enter to continue.
Build 'qemu' errored: Build was halted.

==> Some builds didn't complete successfully and had errors:
--> qemu: Build was halted.

==> Builds finished but no artifacts were created.
```

**Comment by tmatilai** [comment]
The issue here seems to be that qemu on OS X doesn't support KVM. But I'm currently testing if I can get the boxes built in Hashicorp Atlas. So far looks good.

Anyway I'm going to merge this and port the support for OpenBSD 5.7.

**Comment by tmatilai** [comment]
The libvirt boxes for [5.7](https://atlas.hashicorp.com/tmatilai/boxes/openbsd-5.7) and [5.6](https://atlas.hashicorp.com/tmatilai/boxes/openbsd-5.6) should now be available in Atlas. It would be great if @thypon (or someone else) could test if they actually work.

**Pull request merged**
