### PR TITLE
Create openbsd-5.9-amd64.json

### PR DESCRIPTION
**Pull request by ryanmaclean**
Adding AMD64 5.9 for selfish reasons. Can backfill x86 for same and 5.8 if needed.

### CODE REVIEW

**Comment by zigg** [comment]
I apologize that we're not keeping up with this repo, but there are now three different PRs to add 5.9 support: #22, #23, and #24.

Can we bring these together?

**Comment by ryanmaclean** [comment]
I'm down with it - I'm also down with forking and sending regular PRs :)

**Comment by heichblatt** [comment]
I'll close my PR, then. Thanks @ryanmaclean.

**Comment by heichblatt** [comment]
Hello again, what can we do to get this merged?

**Comment by ryanmaclean** [comment]
Shall I update mine to 6.0?

**Comment by heichblatt** [comment]
Hi @tmatilai ,

do you even use this repo anymore?

@ryanmaclean I'm tending towards using your fork as the authoritative for my purposes. You're going to update it regularly, it seems?

Cheers

**Comment by tmatilai** [comment]
> do you even use this repo anymore?

No... I haven't used nor developed Vagrant for a long time, and neither needed OpenBSD. So this repo has been mainly maintained by @zigg and @carletes.

I'm happy to add more contributors to the repo. Or if you feel it would be better, I can also move the ownership. IMHO fork is a worse option. By moving Github sets redirects, transfers stars etc.

**Comment by heichblatt** [comment]
Hi @tmatilai,

I didn't see that, my fault. If that's fine with you, I'd be happy to take a look at any new pull requests and merge them if necessary. Feel free to add me.

Cheers for the work so far :)

**Comment by tmatilai** [comment]
@heichblatt, done! See also #25 

And I also forgot @dentarg from the maintainer list. Sorry!

**Comment by heichblatt** [comment]
Thanks @ryanmaclean.

And thank you @tmatilai. :)

**Pull request merged**
